heat_template_version: 2016-10-14

description: >
  HOT template that invokes subtemplates

parameters:
  key_name:
    type: string
    description: Name of keypair to assign to servers
  image_linux:
    type: string
    description: Name of image to use for GNU/Linux servers
    default: Ubuntu Server 18.04 LTS (Bionic Beaver) amd64
  sec_group_linux:
    type: comma_delimited_list
    description: Security groups
    default: default,linux
  public_net:
    type: string
    description: >
      ID or name of public network for which floating IP addresses will be allocated
    default: ntnu-internal
 
resources:

  manager:
    type: manager.yaml
    properties:
      key_name:          { get_param: key_name }
      image_linux:       { get_param: image_linux }  
      public_net:        { get_param: public_net }  
      sec_group_linux:   { get_param: sec_group_linux }

  minions:
    type: minions.yaml
    depends_on: manager
    properties:
      key_name:          { get_param: key_name }
      image_linux:       { get_param: image_linux }  
      sec_group_linux:   { get_param: sec_group_linux }  
      public_net:        { get_param: public_net }  
      test_admin_net:         { get_attr: [manager,test_admin_net] }
      test_admin_subnet:      { get_attr: [manager,test_admin_subnet] }
      dns_ip:            { get_attr: [manager,manager_admin_ip] }
      manager_ip:        { get_attr: [manager,manager_admin_ip] }

outputs:
  manager_admin_ip:
    description: IP address of manager in the admin network
    value: { get_attr: [manager,manager_admin_ip] }
