heat_template_version: 2016-10-14


description: >
  infrastructure, Note: THIS DEPENDS ON manager.yaml

parameters:
  key_name:
    type: string
    description: Name of keypair to assign to servers
  image_linux:
    type: string
    description: Name of image to use for servers
  sec_group_linux:
    type: comma_delimited_list
    description: Security groups
  public_net:
    type: string
    description: >
      ID or name of public network for which floating IP addresses will be allocated
  test_admin_net:
    type: string
    description: UUID of admin net created in base template (pled_admin_net)
  test_admin_subnet:
    type: string
    description: UUID of admin subnet created in base template (192.168.180.0/24)
  dns_ip:
    type: string
    description: IP address of dns server created in base template
  manager_ip:
    type: string
    description: IP address of server manager created in base template


resources:

  balancer:
    type: lib/managed_linux_server.yaml
    properties:
      server_name:       web-api-balancer
      key_name:          { get_param: key_name }
      image:             { get_param: image_linux }
      flavor:            t1.medium
      sec_group_linux:   { get_param: sec_group_linux }  
      public_net:        { get_param: public_net }  
      test_admin_net:         { get_param: test_admin_net }
      test_admin_subnet:      { get_param: test_admin_subnet }
      dns_ip:            { get_param: dns_ip }
      manager_ip:        { get_param: manager_ip }

  # web-api:
  #   type: lib/managed_linux_server.yaml
  #   properties:
  #     server_name:       web-api
  #     key_name:          { get_param: key_name }
  #     image:             { get_param: image_linux }
  #     flavor:            t1.medium
  #     sec_group_linux:   { get_param: sec_group_linux }
  #     public_net:        { get_param: public_net }
  #     test_admin_net:         { get_param: test_admin_net }
  #     test_admin_subnet:      { get_param: test_admin_subnet }
  #     dns_ip:            { get_param: dns_ip }
  #     manager_ip:        { get_param: manager_ip }

  # dbreplica:
  #   type: lib/managed_linux_server.yaml
  #   properties:
  #     server_name:       dbreplica
  #     key_name:          { get_param: key_name }
  #     image:             { get_param: image_linux }
  #     flavor:            t1.medium
  #     sec_group_linux:   { get_param: sec_group_linux }
  #     public_net:        { get_param: public_net }
  #     test_admin_net:         { get_param: test_admin_net }
  #     test_admin_subnet:      { get_param: test_admin_subnet }
  #     dns_ip:            { get_param: dns_ip }
  #     manager_ip:        { get_param: manager_ip }

  # docker-registry:
  #   type: lib/managed_linux_server.yaml
  #   properties:
  #     server_name:       docker_registry-test
  #     key_name:          { get_param: key_name }
  #     image:             { get_param: image_linux }
  #     flavor:            t1.medium
  #     sec_group_linux:   { get_param: sec_group_linux }
  #     public_net:        { get_param: public_net }
  #     test_admin_net:         { get_param: test_admin_net }
  #     test_admin_subnet:      { get_param: test_admin_subnet }
  #     dns_ip:            { get_param: dns_ip }
  #     manager_ip:        { get_param: manager_ip }

  # database-web-interface:
  #   type: lib/managed_linux_server.yaml
  #   properties:
  #     server_name:       database_web_interface
  #     key_name:          { get_param: key_name }
  #     image:             { get_param: image_linux }
  #     flavor:            t1.medium
  #     sec_group_linux:   { get_param: sec_group_linux }
  #     public_net:        { get_param: public_net }
  #     test_admin_net:         { get_param: test_admin_net }
  #     test_admin_subnet:      { get_param: test_admin_subnet }
  #     dns_ip:            { get_param: dns_ip }
  #     manager_ip:        { get_param: manager_ip }